version: '3.3'
services:
  # nest:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   volumes:
  #     - .:/usr/src/app
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: vacancies
  #   # Run a command against the development stage of the image
  #   command: npm run start:dev
  #   ports:
  #     - 3000:3000
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vacancies
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
    # networks:
    #   - vacancies
  postfix:
    image: infrastructr/postfix
    ports:
      - 25:25
  keycloak:
    depends_on:
      - postgres
    container_name: keycloak
    environment:
      PORT_KEYCLOAK: 8080
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    image: bitnami/keycloak:latest
    ports:
      - '8080:8080'
    restart: unless-stopped
#     networks:
#       - vacancies
# networks:
#   vacancies:
